version: '3.4'
services:
  metad:
    image: docker.io/vesoft/nebula-metad:v3.6.0
    environment:
      USER: root
      TZ:  UTC
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=metad
      - --ws_ip=metad
      - --port=9559
      - --ws_http_port=19559
      - --data_path=/data/meta
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://metad:19559/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9559:9559
      - 19559:19559
      - 19560
    volumes:
      - ${DATA_DIR}/data/meta:/data/meta:rw
      - ${DATA_DIR}/logs/meta:/logs:rw
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  storaged:
    image: docker.io/vesoft/nebula-storaged:v3.6.0
    environment:
      USER: root
      TZ:  UTC
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=storaged
      - --ws_ip=storaged
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    depends_on:
      - metad
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://storaged:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9779:9779
      - 19779:19779
      - 19780
    volumes:
      - ${DATA_DIR}/data/storage:/data/storage:rw
      - ${DATA_DIR}/logs/storage:/logs:rw
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  graphd:
    image: docker.io/vesoft/nebula-graphd:v3.6.0
    environment:
      USER: root
      TZ:  UTC
    command:
      - --meta_server_addrs=metad:9559
      - --port=9669
      - --local_ip=graphd
      - --ws_ip=graphd
      - --ws_http_port=19669
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    depends_on:
      - storaged
      - metad
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://graphd:19669/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 9669:9669
      - 19669:19669
      - 19670
    volumes:
      - ${DATA_DIR}/logs/graph:/logs:rw
    networks:
      - nebula-net
    restart: on-failure
    cap_add:
      - SYS_PTRACE

    
  listener0:
    image: vesoft/nebula-storaged:v3.6.0
    depends_on:
      - metad
    environment:
      USER: root
      TZ:  UTC
    entrypoint: ["/usr/local/nebula/bin/nebula-storaged"]
    command:
      - --flagfile=/usr/local/nebula/etc/nebula-storaged-listener.conf.production
      - --daemonize=false
      - --containerized=true
      - --meta_server_addrs=metad:9559
      - --local_ip=172.10.10.101
      - --ws_ip=172.10.10.101
      - --port=9789
      - --ws_http_port=19789
      - --data_path=/data/listener
      - --log_dir=/logs
      - --stdout_log_file=storaged-listener-stdout.log
      - --stderr_log_file=storaged-listener-stderr.log
      - --minloglevel=0
      - --v=0
      - --redirect_stdout=true
      - --timestamp_in_logfile_name=true
    ports:
      - "9789:9789"
      - 19789
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://listener:19789/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ${DATA_DIR}/data/listener:/data/listener:rw
      - ${DATA_DIR}/logs/listener:/logs:rw
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    logging:
        driver: "json-file"
        options:
          max-size: "100k"
          max-file: "5"
    ### 由于Nebula 全文索引服务只支持使用IP地址访问，所以需要指定子网和网关
    networks:
        nebula-net:
          ipv4_address: 172.10.10.101

# Refer https://docs.nebula-graph.com.cn/3.6.0/4.deployment-and-installation/6.deploy-text-based-index/2.deploy-es/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - ES_PORT=0.0.0.0:9200
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - action.auto_create_index=+*
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - 9200:9200
    depends_on:
      - graphd
    volumes:
      - ${DATA_DIR}/data/elasticsearch:/usr/share/elasticsearch/data:rw
      - ${DATA_DIR}/logs/elasticsearch:/usr/share/elasticsearch/logs:rw
    restart: on-failure
    cap_add:
      - SYS_PTRACE
    logging:
        driver: "json-file"
        options:
          max-size: "100k"
          max-file: "5"
    ### 由于Nebula 全文索引服务只支持使用IP地址访问，所以需要指定子网和网关
    networks:
        nebula-net:
          ipv4_address: 172.10.10.100

  console:
    image: vesoft/nebula-console:v3.6.0
    entrypoint: ""
    command: 
      - sh
      - -c
      - |
        for i in `seq 1 60`;do
          var=`nebula-console -addr graphd -port 9669 -u root -p nebula -e 'ADD HOSTS "storaged":9779'`;
          if [[ $$? == 0 ]];then
            break;
          fi;
          sleep 1;
          echo "retry to add hosts.";
        done && tail -f /dev/null;
    depends_on:
      - graphd
    networks:
      - nebula-net

  web:
      image: vesoft/nebula-graph-studio:v3.9
      environment:
        USER: root
        UPLOAD_DIR: /upload
      depends_on:
        - graphd
      ports:
        - 7001:7001
      volumes:
        - ${DATA_DIR}/upload:/upload:rw
      networks:
        - nebula-net
      restart: on-failure
      cap_add:
        - SYS_PTRACE
      logging:
        driver: "json-file"
        options:
          max-size: "100k"
          max-file: "5"
          
  http_gateway:
      image: kineviz/nebula-http-gateway:latest
      environment:
        DB_ADDRESS: graphd
        DB_PORT: 9669
      ports:
        - 8080:8080
      depends_on:
        - graphd
        - elasticsearch
      networks:
        - nebula-net
      restart: on-failure
      cap_add:
        - SYS_PTRACE
      logging:
        driver: "json-file"
        options:
          max-size: "100k"
          max-file: "5"

networks:
  nebula-net:
    external: true